### ISSUE TITLE
Use flavor parser from Docs/DesignDocs/tools/flavor-name-check.

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/gx-credential-generator#15]
In https://github.com/SovereignCloudStack/Docs/blob/main/Design-Docs/tools/flavor-name-check.py we do have the capability to parse SCS conformant flavor names which may expose a lot more details than we normally have from the OpenStack flavor list (even with the poorly standardized extra_specs).
We should use this to fill in extra data and expose it via Gaia-X attributes.

**Comment by garloff** [comment]
See
https://docs.openstack.org/api-guide/compute/extra_specs_and_properties.html

**Comment by anjastrunk** [comment]
done as part of #78
