### ISSUE TITLE
Align Flavor description between SCS and Gaia-X

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/gx-credential-generator#63]
OpenStack flavors come with a variety of properties, from which the following (according to [Flavor Naming Standard V3](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md) are the most important ones:

* CPU Generation
* Number of virtual CPUs
* Amount of memory available for the VM
* Ability to label high-performance CPUs, disks, network
* CPU Type (X86-intel, X86-amd, ARM, RISC-V, Generic)
* Bare Metal System (no virtualization/hypervisor)

As a provider, I want to publish my flavor properties within a Gaia-X Credential. Gaia-X Credential schema has to provide appropriate vocabulary to describe flavor properties from above.

**Comment by anjastrunk** [comment]
Gaia-X models Flavors as `ServerFlavor` with dedicates attributes for cpu, gpu and ram and disk properties. 

```mermaid
classDiagram

InstantiationRequirement <|-- ServerFlavor

ServerFlavor --> CPU
ServerFlavor --> GPU
ServerFlavor --> Disk
```

**Comment by anjastrunk** [comment]
Systematic flavor naming is defined in [Flavor Naming Standard](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md#complete-proposal-for-systematic-flavor-naming). I will explain mapping from SCS to Gaia-X and vice versa in the following.

**Comment by anjastrunk** [comment]
### CPUs & Suffix:

**Number of virtual (Virtual Machine) or physical (Bare Metal Machines) CPUs - N**:

Gaia-X Credential Schema contains class `ServerFlavor`, which specifies number of CPUs and their properties via attribute `cpu`. The attribute is required and can be set several time. The count of attribute `cpu` correspond to *N* in SCS Flavor naming standard.  

**CPU suffix - L/T/C**:

**Comment by anjastrunk** [comment]
### Memory:

**Comment by anjastrunk** [comment]
## Hypervisor:

SCS defines used hypervisor with an additional, optional suffix. Gaia-X models hypervisors as any other software used in cloud infrastructures as [Software Resource](https://gitlab.com/gaia-x/technical-committee/service-characteristics/-/blame/262-transform-virtual-machine-service-offering-to-linkml/single-point-of-truth/22.10/resource.yaml#L83). 

Currently, there is no dedicated attribute in class [Server Flavor](https://gitlab.com/gaia-x/technical-committee/service-characteristics/-/blob/262-transform-virtual-machine-service-offering-to-linkml/single-point-of-truth/22.10/server-flavor.yaml) to define used hypervisor. I added one, see [!190](https://gitlab.com/gaia-x/technical-committee/service-characteristics/-/merge_requests/190)

**Comment by anjastrunk** [comment]
## CPU Architecture Details

### Vendor

### Generation


### Frequency


### Mapping SCS to Gaia-X

**Comment by anjastrunk** [comment]
## GPU Support

**Comment by garloff** [comment]
> NL 	`cpu` is set n times. 	`defaultOvesubscriptionRatio` = 6
> `smtEnabled` = false
> OR
> `defaultOvesubscriptionRatio` = 4
> `smtEnabled` = true 	As SCS does not support explicit values for oversubstription, maximum values +1 as defined in [SCS Flavor Standard](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md#complete-proposal-for-systematic-flavor-naming) are set for `defaultOversubscription`.

Properties in the SCS flavor standard are *minimally guaranteed* properties, i.e. providers promise to deliver no less than what the specification says. Providers are free to deliver more though.
I assume that Gaia-X properties work the same way. That would mean that translating SCS `L` to Gaia-X `defaultOvesubscriptionRatio = 6` has the risk to overpromise. I would probably set this to `16`.
(Why 16? Building extreme hardware with few cores, e.g. a 32core server and lots of RAM will still not allow to fit unlimited number of `SCS-1L-1` instances, so it's almost guaranteed to never cross this.)

The fact that `defaultOvesubscriptionRatio` lacks an `r` is intentional?

**Comment by anjastrunk** [comment]
> I would probably set this to `16`.

I agree and changed it in above comment accordingly.

**Comment by anjastrunk** [comment]
> The fact that `defaultOvesubscriptionRatio` lacks an `r` is intentional?

No, of course not. It's a typo...
